version: '2.1'
services:
  proxy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    environment:
      - ENVIRONMENT=dev
    ports:
      - 80:80
    restart: always
